---
abstract: 'mark tickets as spam with one click'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ReportSpam
no_index:
  directory:
    - html
    - inc
    - static
requires:
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: '0.13'
x_module_install_rtx_version: 0.34_04
x_requires_rt: 4.0.0
